# Numpy 操作
在本练习中你可以了解大部分常用的 Numpy 运算 (数组和矩阵运算)
np.mat 是 np.array 的子集

- 创建一维数组，获取数组长度，元素，改变元素
- 创建2维数组，获取数组长度，元素，改变元素
- 常用矩阵： 全0矩阵 全1矩阵 常数矩阵 单位矩阵 元素为随机数的矩阵
- 子矩阵视图
- 子矩阵一维、二维视图
- 索引矩阵
- 布尔矩阵
- 矩阵的数学运算，对应元素的数学运算
- 矩阵的点积
- 矩阵的轴
- 矩阵的转置
- 矩阵的内积
- 矩阵的外积

回顾基本概念：

* 向量的运算：

  * 加减、数乘、数量积（点积、内积）、向量积（叉积、外积）

* 对应的英文名称：
  * 叉积： cross product
  * 点积： dot product
  * 内积： inner product | scalar prodct
  * 外积： wedge product | outer product | exterior product
  * 外积的符号是 ^, 英文念作 wedge。
  * 混合积/三重积： triple product

* 点积 a.b = |a| |b| cos(x)
  * 两个矢量a = [a1, a2,…, an]和b = [b1, b2,…, bn]的点积定义为：
    a·b=a1b1+a2b2+……+anbn
    使用矩阵乘法并把（纵列）矢量当作n×1 矩阵，点积还可以写为：
    a·b=a^T*b，这里的a^T指示矩阵a的转置。
  * 点积的值由以下三个值确定：u的大小、v的大小、u,v夹角的余弦。    
    * 在u,v非零的前提下，    
      * 点积如果为负，则u,v形成的角大于90度；
      * 如果为零，那么u,v垂直；
      * 如果为正，那么u,v形成的角为锐角。
      
  * 用途
    * 点积得到两个向量的夹角的cos值，通过它可以知道两个向量的相似性，利用点积可判断一个多边形是否面向摄像机还是背向摄像机
    * 向量的点积与它们夹角的余弦成正比，因此在聚光灯的效果计算中，可以根据点积来得到光照效果，如果点积越大，说明夹角越小，则物理离光照的轴线越近，光照越强。
    * 物理中，点积可以用来计算合力和功。若b为单位矢量，则点积即为a在方向b的投影，即给出了力在这个方向上的分解。功即是力和位移的点积。
    * 计算机图形学常用来进行方向性判断，如两矢量点积大于0，则它们的方向朝向相近；如果小于0，则方向相反。
    * 矢量内积是人工智能领域中的神经网络技术的数学基础之一，此方法还被用于动画渲染（Animation-Rendering）。
  
  
* 比较内积、外积，在几何代数中，

  * 内积是降阶操作，两个矢量的内积是标量（一个数），内积的结果定义在空间里，
  * 外积是升阶操作，两个矢量的外积是二阶矢量，外积的结果则不是定义在空间里，是定义在另外的空间的。
  
* 叉积：a×b（有时也被写成a∧b，避免和字母x混淆），
  * |向量a×向量b|=|a||b|sinθ在这里θ表示两向量之间的角夹角（0° ≤ θ ≤ 180°），它位于这两个矢量所定义的平面上
  * 是有方向性的，不满足交换律，叉积交换，符号相反
  * 几何意义
    * 叉积的长度 |a×b| 可以解释成以a和b为邻边的平行四边形的面积。
    * 混合积 [a b c] = (a×b)·c，使用内积和外积，能够定义混合积：(a×b)·c，参照叉乘的几何意义，混合积的几何意义表示以a，b，c为棱的平行六面体的体积。
  * 代数规则
    * 反交换律：a×b= -b×a
    * 加法的分配律：a× (b+c) =a×b+a×c
    * 与标量乘法兼容：(ra) ×b=a× (rb) = r(a×b)
    * 不满足结合律，但满足雅可比恒等式：a× (b×c) +b× (c×a) +c× (a×b) =0
    * 分配律，线性性和雅可比恒等式别表明：具有向量加法和叉积的 R3 构成了一个李代数。
    * 两个非零向量 a 和 b 平行，当且仅当a×b=0
  * 拉格朗日公式
    这是一个著名的公式，而且非常有用： a× (b×c) =b(a·c) -c(a·b)
  * 应用
    在物理学光学和计算机图形学中，叉积被用于求物体光照相关问题。
    求解光照的核心在于求出物体表面法线，而叉积运算保证了只要已知物体表面的两个非平行矢量(或者不在同一直线的三个点),就可依靠叉积求得法线。
    
* 矩阵有几个特有的属性使得计算更加容易，这些属性有：
        (a) .T －－ 返回自身的转置
        (b) .H －－ 返回自身的共轭转置
        (c) .I －－ 返回自身的逆矩阵
        (d) .A －－ 返回自身数据的2维数组的一个视图（没有做任何的拷贝）  
        
* 点积运算律
    * 1.交换律：α·β=β·α　
    * 2.分配律：(α+β)·γ=α·γ+β·γ　
    * 3.若λ为数：(λα)·β=λ(α·β)=α·(λβ)　若λ、μ为数：：(λα)·(μβ)=λμ(α·β)　
    * 4.α·α=|α|^2 ，此外：α·α=0〈=〉α=0。　
    
    向量的数量积不满足消去律，即一般情况下：α·β=α·γ，α≠0 ≠〉β=γ。　向量的数量积不满足结合律，即一般（α·β)·γ ≠〉α·（β·γ）　相互垂直的两向量数量积为0

* 笛卡尔积是两个集合中元素的全影射；
* 卷积是两个向量折返乘积的和；
* to be completed， 更多请参考 https://github.com/mebusy/notes/blob/master/dev_notes/LinearAlgebra.md

In [3]:
import numpy as np # 经常引用，用缩写更方便，以下每部分都需要这一行，所以单独列出，下面不再重复

In [9]:
#创建一维数组，获取数组长度，元素，改变元素

a = np.array([1, 2, 3])   # 创建一维数组
print(type(a))            # 输出 "<class 'numpy.ndarray'>"
print(a.shape)            # 输出 "(3,)"
print(a[0], a[1], a[2])   # 输出 "1 2 3"
a[0] = 5                  # 改变数组中的一个元素
print(a)                  # 输出 "[5 2 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [10]:
#创建2维数组，获取数组长度，元素，改变元素
b = np.array([[1,2,3],[4,5,6]])    # 创建2维数组
print(b.shape)                     # 输出 "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # 输出 "1 2 4"
b[1,2] = 7                # 改变数组中的一个元素
print(b)                  # 输出 "[[1 2 3] [4 5 7]]"

(2, 3)
1 2 4
[[1 2 3]
 [4 5 7]]


In [53]:
#常用矩阵
a = np.zeros((2,2))   # 创建一个全0矩阵
print(a)              # 输出 "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # 创建一个全1矩阵
print(b)              # 输出 "[[ 1.  1.]]"

c = np.full((2,2), 9)  # 创建一个常数矩阵,python 3.5 下会有一 FutureWarning
                       #      FutureWarning: in the future, full((2, 2), 9) will return an array of dtype('int64')
print(c)               # 输出 "[[ 9.  9.]
                       #          [ 9.  9.]]"

ci = np.full((2,2), 9, dtype = np.int64)  # 以上会有一 warning, 我们可以指定数据类型 int64， 创建一个常数矩阵
print(ci)              # 输出 "[[ 9  9]
                       #          [ 9  9]]"

cf = np.full((2,2), 9, dtype = np.float64)  # 指定数据类型 float64， 创建一个常数矩阵
print(cf)              # 输出 "[[ 9.  9.]
                       #          [ 9.  9.]]"  
    
d = np.eye(2)         # 创建一个2x2单位矩阵
print(d)              # 输出 "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # 创建一个矩阵，元素为随机数
print(e)                     # 可能 输出 "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"
    
# 利用arange来创建一个一维整数矩阵, 比较 f 和 g
f = np.arange(4)
print(f)      # 没逗号，是矩阵,输出 "[0 1 2 3]"

flike = list(range(4)) # 比较 arange 和 range
print(flike)      # 有逗号，是列表,输出 "[0, 1, 2, 3]"  

g = np.empty_like(a)
print(g)          #输出 [[ 0.  0.]
                  #     [ 0.  0.]]

h = np.empty_like(b)
print(h)           #输出 [[ 1.  1.]] 

x = np.array([[1,2,3]])
h = np.empty_like(x)
print(h)          #输出 [[1 2 3]]  注意如果某个维度上尺寸为0，则原样输出，这比较奇怪, does it mean to be so?

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 9.  9.]
 [ 9.  9.]]
[[9 9]
 [9 9]]
[[ 9.  9.]
 [ 9.  9.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.23363862  0.45123399]
 [ 0.25563663  0.42205855]]
[0 1 2 3]
[0, 1, 2, 3]
[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[1 2 3]]


/usr/lib/python3/dist-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 9) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [12]:
#矩阵赋值与子矩阵视图

# 创建一个3X4二维矩阵
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print('-----')
# 取子矩阵2X2:
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)
print('-----')
# 子矩阵其实是原矩阵的一个视图，数据一样，就像指针指到了同一个存储空间，如果改变子矩阵，会改变原矩阵
print(a[0, 1])   # 输出 "2"
print('-----')
b[0, 0] = 0     # b[0, 0] 的数据和 a[0, 1]一致
print(a[0, 1])   # 输出 "0"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----
[[2 3]
 [6 7]]
-----
2
-----
0


In [17]:
#矩阵赋值与子矩阵一维、二维视图，很搞

# 创建一个3X4二维矩阵
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 两种截取子矩阵的方法，对行操作:
row_r1 = a[1, :]    # a 第2行的一维视图
row_r2 = a[1:2, :]  # a 第2行的2维视图，取1行，其中 1 <= 行索引 < 2, 行索引的取值范围表示成数学集合范围为： [1,2)
row_r2_2 = a[1:3, :]  # a 第2行的2维视图，取2行
print(row_r1, row_r1.shape)  # 输出 "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # 输出 "[[5 6 7 8]] (1, 4)"
print(row_r2_2, row_r2_2.shape)  # 输出 "[[ 5  6  7  8]
                                 #       [ 9 10 11 12]] (2, 4)"

# 两种截取子矩阵的方法，对列操作:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # 输出 "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # 输出 "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[ 5  6  7  8]
 [ 9 10 11 12]] (2, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [20]:
#矩阵赋值与索引矩阵， 总的来说就是【为了偷懒少写几个字搞的缩写映射】
a = np.array([[1,2], [3, 4], [5, 6]])
print(a) # 输出  [[1 2]
         #      [3 4]
         #     [5 6]]
        
# 索引二维矩阵，很搞，以下返回3列一维矩阵 (3,) 
print(a[[0, 1, 2], [0, 1, 0]])  # 输出 "[1 4 5]"

# 上面的索引矩阵索引等于:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # 输出 "[1 4 5]"

# 再来一边，
print(a[[0, 0], [1, 1]])  # 输出 "[2 2]"

# 上面的索引矩阵索引等于:
print(np.array([a[0, 1], a[0, 1]]))  # 输出 "[2 2]"

# 多练几次，再来一个，如果现在要输出[3 6 1]，该怎么办呢？ 可以作为奥数题测试下小朋友
print(a[[1,2,0], [0,1,0]])  # 输出 "[3 6 1]"

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]
[3 6 1]


* 思考： 用以上这种方法如何输出（，3）矩阵呢？

In [28]:
# 数据矩阵和索引矩阵
# 承上，把索引矩阵放到另一个矩阵名字里，为什么要这么做呢？ 
# 想想图片那庞大的多维矩阵， 128层的神经网络，如果不单独管理索引，运算的时候引用起来会很凌乱
# 再想想邮政管理，已经有了道路编号，但我们还是需要邮政编号，这算是一种高维度的管理思维吧

# 创建矩阵，这个矩阵用于存放数据
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # 输出 "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# 创建矩阵，这个矩阵用于存放索引
b = np.array([0, 2, 0, 1])

# 组成索引矩阵，获取数据，每一行取一个数据，每一行取哪一列取决于 b
# a[[0,1,2,3],[0, 2, 0, 1]]
print(a[np.arange(4), b])  # 输出 "[ 1  6  7 11]"

# 组成索引矩阵，对矩阵中的数据赋值，每一行改变一个数据，每一行改变哪一列取决于 b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [30]:
#数据矩阵和布尔矩阵
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
bool_idx = (a > 2)   # 寻找矩阵 a 中大于 2 的元素，这个运算会返回一个 a 同样大小的布尔矩阵

print(bool_idx)      # 输出    "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# 这个布尔矩阵可以用来获取矩阵a的子矩阵，获取其 True 对应的元素
print(a[bool_idx])  # 输出 "[3 4 5 6]"

# 以上可以缩写成一行，想想这个方法会用到哪里呢？ :
print(a[a > 2])     # 输出 "[3 4 5 6]"


[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [33]:
# 再来一边： 数据矩阵和布尔矩阵
a = np.array([[1,2,3],[7,8,9],[4,5,6],[10,11,12]])
print(a)  # 输出 [[ 1  2  3]
          #      [ 7  8  9]
          #      [ 4  5  6]
          #      [10 11 12]]
            
bool_idx = (a > 5)   # 寻找矩阵 a 中大于 2 的元素，这个运算会返回一个 a 同样大小的布尔矩阵

print(bool_idx)      # 输出    "[[False False False]
                     #          [ True  True  True]
                     #          [False False  True]
                     #          [ True  True  True]]"

# 这个布尔矩阵可以用来获取矩阵a的子矩阵，获取其 True 对应的元素
print(a[bool_idx])  # 输出 "[ 7  8  9  6 10 11 12]"

# 高个挑出来排成一排 :
print(a[a > 5])     # 输出 "[ 7  8  9  6 10 11 12]"


[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]
[[False False False]
 [ True  True  True]
 [False False  True]
 [ True  True  True]]
[ 7  8  9  6 10 11 12]
[ 7  8  9  6 10 11 12]


In [36]:
# 矩阵的数学运算，点到点的数学运算
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# 对应元素相加，输出
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# 对应元素相减，输出
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# 对应元素相乘，输出
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# 对应元素相除，输出
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# X 矩阵元素开平方，输出
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [39]:
# 二维矩阵和一维矩阵的点积
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x) #输出 [[1 2]   # --
         #    [3 4]]  # __
print(y) #输出 [[5 6]
         #    [7 8]]  #     | |

v = np.array([9,10])
w = np.array([11, 12])

# 向量内积和; 输出 219 = 9*11 + 10*12
print(v.dot(w))
print(np.dot(v, w))

# 矩阵/向量乘积; 输出  [29 67] = [1*9+2*10 3*9+4*10]
print(x.dot(v))
print(np.dot(x, v))

# 矩阵/向量乘积; 输出 
# [[19 22]     
#  [43 50]]  
#  运算过程如下
#  --  |  
#  --     |
#  __  |  
#  __     |  
#  19 = 1*5 + 2*7   22 = 1*6 + 2*8
#  43 = 3*5 + 4*7   50 = 3*6 + 4*8
print(x.dot(y))
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [40]:
#矩阵的轴， 列0行1
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # 所有元素相加，输出 "10"
print(np.sum(x, axis=0))  # 各列所有元素相加，输出 "[4 6]"
print(np.sum(x, axis=1))  # 各行所有元素相加，输出 "[3 7]"

10
[4 6]
[3 7]


* 思考： 这个轴的先后次序是怎么来的？

In [63]:
#矩阵转置
x = np.array([[1,2], [3,4]])
print(x)    # 输出 "[[1 2]
            #          [3 4]]"
print(x.T)  # 输出 "[[1 3]
            #          [2 4]]"

# 注意：一维矩阵转置还是原状:
v = np.array([1,2,3])
print(v)    # 输出 "[1 2 3]"
print(v.T)  # 输出 "[1 2 3]"


# 那么怎么变成一个3行1列矩阵呢？加个维度:
w = np.array([[1,2,3]])
print(w)    # 输出 "[[1 2 3]]"
print(w.T)  # 输出 "[[1]
            #       [2]
            #       [3]]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [65]:
# 把向量 v 加到矩阵 x 上，在矩阵 y 中存储结果
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # 创建一个和 x 同维度大小的空矩阵

print(x)
print(v)
print(y)

#输出：
#[[ 1  2  3]
# [ 4  5  6]
# [ 7  8  9]
# [10 11 12]]
#[1 0 1]
#[[0 0 0]  #疑似 bug *
# [0 0 0]
# [0 0 0]
# [0 0 0]]

# 给矩阵的每一行加上向量 v
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)
# 输出
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]


w = np.zeros(x.shape)  # 创建一个和 x 同维度大小的实数空矩阵, it's much more stable
print(w)               # [[ 0.  0.  0.]
                       # [ 0.  0.  0.]
                       # [ 0.  0.  0.]
                       # [ 0.  0.  0.]]

z = np.empty_like(x)   # 创建一个和 x 同维度大小的整数空矩阵, this is to check if there's a bug of empty_like
print(z)               # [[0 0 0]
                       # [0 0 0]
                       # [0 0 0]
                       # [0 0 0]]      

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


疑似 bug *: python 3.5.2  re-run after running this round, the output will be the same as x, it should be a bug of np.empty_like(). It can be repeated, but does not come out every time.

In [68]:
# 把向量 v 加到矩阵 x 上，在矩阵 y 中存储结果, tile 方法用来堆叠
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # 叠4行
print(vv)                 # 输出 "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  #  x 和 vv 各元素相加
print(y)  # 输出 "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:

# 计算向量外积
v = np.array([1,2,3])  # v 的 shape (3,)
w = np.array([4,5])    # w 的 shape (2,)
# 为了计算外积, 首先将 v 变成一个 (3, 1) 的向量; 将其和 相乘为 (3, 2)的向量,  v 和 w 的外积为:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

In [69]:
x = 1.746
y_tanh = np.tanh(x)

print(x,' ',y_tanh)

1.746   0.940918571843


In [5]:
'''
[[2 2 1 1]
 [2 2 1 1]
 [1 1 2 2]
 [1 1 2 2]]
'''
A=np.mat('2 2; 2 2'); B=np.mat('1 1; 1 1');
print(np.bmat('A B; B A'))
 

[[2 2 1 1]
 [2 2 1 1]
 [1 1 2 2]
 [1 1 2 2]]


In [11]:
#由一维或二维数据创建矩阵
a1=array([1,2,3])
print(a1)
b=matrix([1,2,3])
print(b)

[1 2 3]
[[1 2 3]]


In [13]:
#常见的矩阵运算
#1. 矩阵相乘
a1=mat([1,2]);      
a2=mat([[1],[2]]);
a3=a1*a2 #1*2的矩阵乘以2*1的矩阵，得到1*1的矩阵
print(a3) #matrix([[5]])

#2. 矩阵点乘
#矩阵对应元素相乘
a1=mat([1,1]);
a2=mat([2,2]);
a3=multiply(a1,a2)
print(a3) #matrix([[2, 2]])

[[5]]
[[2 2]]


In [18]:
#3.矩阵求逆，转置
#矩阵求逆
a1=mat(eye(2,2)*0.5)
#matrix([[ 0.5,  0. ],
#        [ 0. ,  0.5]])

a2=a1.I  #求矩阵matrix([[0.5,0],[0,0.5]])的逆矩阵
print(a2)
#matrix([[ 2.,  0.],
#        [ 0.,  2.]])


#矩阵转置
a1=mat([[1,1],[0,0]])
#matrix([[1, 1],
#        [0, 0]])

a2=a1.T
print(a2)
#matrix([[1, 0],
#        [1, 0]])

[[ 2.  0.]
 [ 0.  2.]]
[[1 0]
 [1 0]]


In [ ]:
#4.计算矩阵对应行列的最大、最小值、和。

a1=mat([[1,1],[2,3],[4,2]])
#matrix([[1, 1],
#        [2, 3],
#        [4, 2]])

#计算每一列、行的和
a2=a1.sum(axis=0) #列和，这里得到的是1*2的矩阵
print(a2)
#matrix([[7, 6]])
a3=a1.sum(axis=1) #行和，这里得到的是3*1的矩阵
print(a3)
#matrix([[2],
#        [5],
#        [6]])
a4=sum(a1[1,:])  #计算第一行所有列的和，这里得到的是一个数值
print(a4)
#5                    #第0行：1+1；第2行：2+3；第3行：4+2

#计算最大、最小值和索引
print(a1.max())   #计算a1矩阵中所有元素的最大值,这里得到的结果是一个数值
a2=max(a1[:,1]) #计算第二列的最大值，这里得到的是一个1*1的矩阵
print( a2)
#matrix([[3]])
a1[1,:].max()  #计算第二行的最大值，这里得到的是一个数值
print (a1) #3
print(np.max(a1,0))  #计算所有列的最大值，这里使用的是numpy中的max函数
                                 #matrix([[4, 3]])
print(np.max(a1,1))  #计算所有行的最大值，这里得到是一个矩阵
                                 #matrix([[1],
                                 #        [3],
                                 #        [4]])
print(np.argmax(a1,0)) #计算所有列的最大值对应在该列中的索引
                                 #matrix([[2, 1]])
print(np.argmax(a1[1,:]))  #计算第二行中最大值对应在该行的索引
                                         # 1

In [19]:
#5.矩阵的分隔和合并
#矩阵的分隔，同列表和数组的分隔一致。
#a=mat(ones((3,3)))
print( a)
#matrix([[ 1.,  1.,  1.],
#        [ 1.,  1.,  1.],
#        [ 1.,  1.,  1.]])
b=a[1:,1:]  #分割出第二行以后的行和第二列以后的列的所有元素
print(b)
# matrix([[ 1.,  1.],
#         [ 1.,  1.]])

 

#矩阵的合并


a=mat(ones((2,2)))
print( a)
# matrix([[ 1.,  1.],
#       [ 1.,  1.]])
b=mat(eye(2))
print(b)
#matrix([[ 1.,  0.],
#       [ 0.,  1.]])
c=vstack((a,b))  #按列合并，即增加行数
print(c)
#matrix([[ 1.,  1.],
#        [ 1.,  1.],
#        [ 1.,  0.],
#        [ 0.,  1.]])
d=hstack((a,b))  #按行合并，即行数不变，扩展列数
print(d)
#matrix([[ 1.,  1.,  1.,  0.],
#        [ 1.,  1.,  0.,  1.]])

[[1 2 3]
 [4 5 3]]
[[5 3]]
[[ 1.  1.]
 [ 1.  1.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  0.]
 [ 0.  1.]]
[[ 1.  1.  1.  0.]
 [ 1.  1.  0.  1.]]


In [22]:
dimension=a.ndim
print(dimension)
m,n=a.shape
print(m,n)
number=a.size #元素总个数
print(number)
str=a.dtype #元素的类型
print(str)

2
2 2
4
float64


In [23]:
#矩阵与数组之间的转换：
a1=[[1,2],[3,2],[5,2]]  #列表
print(a1)
#[[1, 2], [3, 2], [5, 2]]
a2=array(a1)  #将列表转换成二维数组
print(a2)
#array([[1, 2],
#       [3, 2],
#       [5, 2]])
a3=mat(a1)  #将列表转化成矩阵
print(a3)
#matrix([[1, 2],
#        [3, 2],
#        [5, 2]])
a4=array(a3)  #将矩阵转换成数组
print(a4)
#array([[1, 2],
#       [3, 2],
#       [5, 2]])
a41=a3.getA()  #将矩阵转换成数组
print(a41)
#array([[1,2]
#       [3,2]
#       [5,2]])
a5=a3.tolist()  #将矩阵转换成列表
print(a5)
#[[1, 2], [3, 2], [5, 2]]
a6=a2.tolist()  #将数组转换成列表
print(a6)
#[[1, 2], [3, 2], [5, 2]]

[[1, 2], [3, 2], [5, 2]]
[[1 2]
 [3 2]
 [5 2]]
[[1 2]
 [3 2]
 [5 2]]
[[1 2]
 [3 2]
 [5 2]]
[[1 2]
 [3 2]
 [5 2]]
[[1, 2], [3, 2], [5, 2]]
[[1, 2], [3, 2], [5, 2]]


In [24]:
dataMat=mat([1])
val=dataMat[0,0]  #这个时候获取的就是矩阵的元素的数值，而不再是矩阵的类型
print(val)

1
