# scipy操作 
在本练习中你可以了解大部分常用的 scipy操作 

In [5]:
# 图片读取，颜色和尺寸变换，存储
from scipy.misc import imread, imsave, imresize

# 将图片读入 numpy 矩阵
img = imread('assets/samples/card19.jpg')
print(img.dtype, img.shape)  # 输出 "uint8 (400, 248, 3)"

# 在三个颜色通道上作尺度变换：乘以 [1, 0.95, 0.9] of shape (3,);
# 即红色通道不变，绿色变为原来的0.95，蓝色变为原来的0.9，
img_tinted = img * [1, 0.95, 0.9]

# 将图片变成 300 * 300 大小。
img_tinted = imresize(img_tinted, (300, 300))

# 保存变换后的图片
imsave('assets/output/card19_tinted.jpg', img_tinted)


uint8 (471, 709, 3)


在 scipy.spatial.distance 中有如下距离， 可以作为 pdist 中的距离类型参数


*   braycurtis       -- the Bray-Curtis distance. 
*   canberra         -- the Canberra distance.
*   chebyshev        -- the Chebyshev distance.
*   cityblock        -- the Manhattan distance.
*   correlation      -- the Correlation distance.
*   cosine           -- the Cosine distance.
*   euclidean        -- the Euclidean distance.
*   mahalanobis      -- the Mahalanobis distance.
*   minkowski        -- the Minkowski distance.
*   seuclidean       -- the normalized Euclidean distance.
*   sqeuclidean      -- the squared Euclidean distance.
*   wminkowski       -- the weighted Minkowski distance.


In [4]:
# 计算距离， 可用于数据分类，比如比较图片相似度
import numpy as np
from scipy.spatial.distance import pdist, squareform

# 输出:
# [[0 1]
#  [1 0]
#  [2 0]]
x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

# 计算欧式距离.
# d[i, j] =  x[i, :] 和 x[j, :]的欧式距离
# 输出:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
d = squareform(pdist(x, 'euclidean'))
print(d)

# 输出
#[[ 0.  2.  3.]
# [ 2.  0.  1.]
3 [ 3.  1.  0.]]
d = squareform(pdist(x, 'cityblock'))
print(d)



[[0 1]
 [1 0]
 [2 0]]
[[ 0.          1.41421356  2.23606798]
 [ 1.41421356  0.          1.        ]
 [ 2.23606798  1.          0.        ]]
[[ 0.  2.  3.]
 [ 2.  0.  1.]
 [ 3.  1.  0.]]
